#!/usr/bin/env python3
"""
Add TFX Engine nitromethane combustion data to the AI Chat Advisor knowledge base.
Technical data and analysis from competitive nitro engine during competition.
"""

import logging
import sys
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s - %(message)s'
)
LOGGER = logging.getLogger(__name__)

project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

try:
    from services.vector_knowledge_store import VectorKnowledgeStore
    from services.knowledge_base_file_manager import KnowledgeBaseFileManager
    KB_AVAILABLE = True
except ImportError as e:
    KB_AVAILABLE = False
    LOGGER.error(f"Knowledge base modules not available: {e}")

# Technical data from TFX Engine nitromethane analysis
NITRO_ENGINE_DATA = [
    {
        "question": "What are typical nitromethane combustion pressures in a competitive drag racing engine?",
        "answer": """Nitromethane produces extremely high combustion pressures compared to gasoline:

**Peak Combustion Pressures:**
- **Nitromethane (96%):** Peak combustion pressure of 4158 psi at 10 ATDC (mid-run)
- **Racing Gasoline:** Only 1500-1800 psi peak combustion pressure
- **Pressure Ratio:** Nitromethane produces approximately 2.3-2.8x higher peak pressures than gasoline

**Pressure Characteristics:**
- Peak pressure occurs around 10 ATDC (After Top Dead Center) during good combustion cycles
- Pressure can vary significantly throughout a run
- Mid-run pressures: 3500-4000 psi per cycle
- Late-run pressures: Can drop to 1000-1500 psi as combustion becomes unstable

**Pressure Location:**
- At start of run: Peak pressure located around 15-20 ATDC
- By end of run: Peak pressure location shifts to 20-25 ATDC
- Location shift indicates combustion timing issues

**Combustion Analysis:**
- Pink line on pressure graph shows pressure without ignition (compression only)
- Blue line shows actual pressure from nitromethane combustion
- The difference represents the power generated by combustion

**Data Source:** Competitive nitro engine during national event, naturally aspirated, operating on 96% nitromethane and 4% methanol mixture.""",
        "keywords": ["nitromethane combustion pressure", "peak pressure", "combustion analysis", "nitro engine data", "psi"],
        "topic": "Nitromethane - Combustion Pressures"
    },
    {
        "question": "How does nitromethane combustion deteriorate during a drag racing run?",
        "answer": """Nitromethane combustion can deteriorate significantly throughout a drag racing run:

**Power Deterioration:**
- **Mid-run (2.568 seconds):** 388 hp/cylinder with peak pressure of 4158 psi
- **Late-run (6.039 seconds):** Only 238 hp/cylinder with peak pressure of 1461 psi
- **Power Loss:** Approximately 38% power loss from mid-run to late-run
- **Pressure Loss:** Peak pressure dropped from 4158 psi to 1461 psi (65% reduction)

**Combustion Instability:**
- Combustion process becomes unstable as run progresses
- Peak pressures decrease from 3500-4000 psi (beginning) to 1000-1500 psi (end)
- Peak pressure location shifts from 15-20 ATDC to 20-25 ATDC
- Substantial cycle-to-cycle variation increases

**Torque Deterioration:**
- Engine torque starts high near 600 ft.lb. at beginning of run
- Deteriorates throughout run to mere 400 ft.lb.
- Cycle-to-cycle variation: +/-10% from average
- Some cylinders may stop firing before end of run

**Cylinder Variation:**
- Different cylinders can have vastly different combustion characteristics
- One cylinder may develop 667 ft.lb. on good cycles
- Same cylinder may have unstable combustion with minimal good cycles
- Cylinders can die before finish line if conditions are poor

**Performance Impact:**
- Significant gains in speed and ET possible by correcting late-run combustion
- Stabilizing combustion throughout entire run is critical
- Equalizing combustion between cylinders improves performance
- Reducing cycle-to-cycle variation increases consistency

**Key Insight:** The combustion process must be stabilized throughout the entire run to maintain power and prevent cylinder failure.""",
        "keywords": ["nitro combustion deterioration", "power loss", "combustion instability", "torque variation", "nitromethane performance"],
        "topic": "Nitromethane - Combustion Deterioration"
    },
    {
        "question": "What is cycle-to-cycle variation in nitromethane engines and why does it matter?",
        "answer": """Cycle-to-cycle variation is a critical issue in nitromethane engines:

**What It Is:**
- Variation in combustion characteristics from one combustion cycle to the next
- Measured in torque, pressure, and power output per cycle
- Can vary by +/-10% from cycle to cycle in unstable conditions

**Impact on Performance:**
- **Torque Variation:** Engine torque can vary significantly between cycles
- **Power Inconsistency:** Power output is not uniform, reducing overall performance
- **Cylinder Differences:** Different cylinders can have vastly different variation levels
- **Combustion Instability:** High variation indicates unstable combustion process

**Real-World Example:**
- Cylinder 1: Torque varies +/-10% from cycle to cycle
- Cylinder 2: Even more cycle-to-cycle variation, stops firing 0.75 seconds before finish
- Good cycles: One cylinder developed 667 ft.lb. on optimal cycle
- Poor cycles: Same cylinder had minimal good cycles during run

**Causes:**
- Unstable fuel mixture
- Inconsistent ignition timing
- Uneven fuel distribution
- Combustion chamber conditions
- Fuel system inconsistencies

**Solutions:**
- Stabilize combustion process throughout entire run
- Equalize combustion between cylinders
- Reduce cycle-to-cycle variation
- Maximize number of good combustion cycles
- Optimize good cycles to generate more torque

**Performance Impact:**
- Reducing variation improves consistency
- More consistent combustion = more predictable power
- Better cylinder-to-cylinder balance = better overall performance
- Stable combustion = maintained power throughout run

**Key Insight:** Cycle-to-cycle variation is a major indicator of combustion quality and directly affects engine performance and reliability.""",
        "keywords": ["cycle to cycle variation", "combustion variation", "torque variation", "nitro engine consistency", "combustion stability"],
        "topic": "Nitromethane - Cycle-to-Cycle Variation"
    },
    {
        "question": "How do nitromethane engines compare to gasoline engines in terms of combustion pressure?",
        "answer": """Nitromethane engines produce dramatically higher combustion pressures than gasoline engines:

**Pressure Comparison:**
- **Nitromethane (96%):** Peak combustion pressure of 4158 psi at 10 ATDC
- **Racing Gasoline:** Peak combustion pressure of only 1500-1800 psi
- **Pressure Ratio:** Nitromethane produces 2.3-2.8x higher peak pressures

**Why This Matters:**
- Higher pressures = more power potential
- Higher pressures = more stress on engine components
- Requires stronger engine components (rods, pistons, bearings, etc.)
- More demanding on fuel system and ignition system

**Combustion Characteristics:**
- Nitromethane burns more completely and rapidly
- Produces more energy per unit of fuel
- Generates higher cylinder pressures
- Creates more torque and horsepower

**Component Requirements:**
- Engine must be built to handle 4000+ psi pressures
- Standard gasoline engine components will fail
- Requires specialized pistons, rods, and bearings
- Head gaskets must be capable of sealing extreme pressures
- Fuel system must deliver adequate volume and pressure

**Performance Trade-offs:**
- Higher pressures = more power
- Higher pressures = more component stress
- Higher pressures = shorter component life
- Higher pressures = more maintenance required

**Data Context:**
- Data from competitive nitro engine during national event
- Naturally aspirated engine
- Operating on 96% nitromethane and 4% methanol
- Peak pressure measured at optimal combustion cycle

**Key Insight:** The extreme pressures generated by nitromethane require specialized engine components and careful tuning to prevent component failure.""",
        "keywords": ["nitro vs gasoline", "combustion pressure comparison", "nitromethane pressure", "engine pressure", "combustion analysis"],
        "topic": "Nitromethane - Pressure Comparison"
    },
    {
        "question": "What are the key areas for improvement in nitromethane engine combustion?",
        "answer": """Key areas for improvement in nitromethane engine combustion based on data analysis:

**1. Stabilize Combustion Process Throughout Entire Run**
- Combustion deteriorates significantly from beginning to end of run
- Power drops from 388 hp/cylinder to 238 hp/cylinder
- Peak pressure drops from 4158 psi to 1461 psi
- Must maintain consistent combustion for entire run duration

**2. Equalize Combustion Process in Each Cylinder**
- Different cylinders have vastly different combustion characteristics
- One cylinder may develop 667 ft.lb. on good cycles
- Another cylinder may stop firing before finish line
- Equal cylinder performance = better overall engine performance

**3. Reduce Cycle-to-Cycle Variation in Combustion Process**
- Torque varies +/-10% from cycle to cycle
- High variation indicates unstable combustion
- Reduces overall power output and consistency
- More uniform cycles = more predictable power

**4. Maximize the Number of Good Combustion Cycles**
- Some cylinders have minimal good cycles during run
- More good cycles = more power throughout run
- Fewer poor cycles = less power loss
- Consistent good cycles = better performance

**5. Further Optimize Good Combustion Cycles to Generate More Torque**
- Good cycles can produce 667 ft.lb. of torque
- Optimizing these cycles can increase power output
- Better combustion timing and mixture = more torque
- More torque = better acceleration and ET

**6. Extend RPM Range Where Good Combustion Can Occur**
- Combustion quality varies with RPM
- Extending good combustion range = more usable power
- Better fuel system and tuning = wider power band
- More RPM range = better performance across track

**Performance Impact:**
- Addressing these areas can significantly improve speed and ET
- Stabilizing late-run combustion prevents power loss
- Equalizing cylinders improves overall engine efficiency
- Reducing variation increases consistency and reliability

**Key Insight:** Systematic improvement in these areas can unlock significant performance gains in nitromethane engines.""",
        "keywords": ["nitro engine improvement", "combustion optimization", "nitromethane tuning", "engine performance", "combustion analysis"],
        "topic": "Nitromethane - Combustion Optimization"
    },
    {
        "question": "What data analysis capabilities are available for nitromethane engines?",
        "answer": """Advanced data analysis capabilities for nitromethane engines:

**Overall Run Summaries:**
- Horsepower (HP) graphs for entire run
- Torque graphs vs. time
- Combustion pressure analysis
- Location of peak combustion pressure relative to TDC
- Volumetric efficiency calculations
- Overall performance metrics

**Individual Cycle Analysis:**
- Pressure vs. crank angle for each combustion cycle
- Pressure vs. crank angle for each non-combustion cycle
- Air/fuel burn rates vs. crank angle
- Numerical data for each cycle:
  * HP for each combustion cycle
  * Peak combustion pressure and location
  * Amount of energy released
  * How efficiently energy was applied

**Multi-Cylinder Comparison:**
- Compare torque between multiple instrumented cylinders
- Compare combustion pressure between cylinders
- Identify cylinder-to-cylinder variations
- Detect cylinders with poor combustion
- Identify cylinders that stop firing early

**Time-Based Analysis:**
- Combustion pressure vs. time
- Torque vs. time
- RPM vs. time
- Peak pressure location vs. time
- Power output vs. time
- Identify deterioration patterns

**Performance Metrics:**
- Peak combustion pressure per cycle
- Peak pressure location (ATDC)
- Torque per cylinder per cycle
- Power per cylinder per cycle
- Energy release efficiency
- Combustion stability metrics

**Diagnostic Capabilities:**
- Identify detonation events
- Detect combustion instability
- Find cycle-to-cycle variation
- Locate combustion timing issues
- Identify fuel system problems
- Detect cylinder-specific issues

**Data Source:**
- Data collected from competitive nitro engine during national event
- Naturally aspirated engine
- Operating on 96% nitromethane and 4% methanol
- Comprehensive logging of all combustion events

**Key Insight:** Comprehensive data analysis is essential for optimizing nitromethane engine performance and identifying areas for improvement.""",
        "keywords": ["nitro data analysis", "combustion data logging", "engine data analysis", "nitromethane telemetry", "performance analysis"],
        "topic": "Nitromethane - Data Analysis"
    },
    {
        "question": "What happens when a nitromethane engine cylinder stops firing during a run?",
        "answer": """When a nitromethane engine cylinder stops firing, it indicates serious combustion problems:

**Symptoms:**
- Cylinder stops firing before finish line (0.75 seconds early in example)
- Combustion process is extinguished before end of run
- Torque drops to zero for that cylinder
- Power output from that cylinder ceases

**Causes:**
- Poor combustion conditions throughout run
- Unstable fuel mixture
- Inconsistent ignition
- Fuel system problems
- Extreme combustion deterioration

**Impact on Performance:**
- Loss of power from that cylinder
- Engine becomes unbalanced
- Overall power output reduced
- ET and speed suffer significantly
- Can cause engine damage if not addressed

**Prevention:**
- Stabilize combustion process throughout entire run
- Equalize combustion between cylinders
- Reduce cycle-to-cycle variation
- Ensure proper fuel delivery to all cylinders
- Maintain consistent ignition timing

**Data Analysis:**
- Can be detected through torque vs. time graphs
- Visible as cylinder torque dropping to zero
- Comparison graphs show which cylinders are failing
- Pressure graphs show loss of combustion pressure

**Real-World Example:**
- Cylinder 2 had poor combustion conditions throughout run
- Stopped firing 0.75 seconds before finish line
- Had minimal good combustion cycles during run
- On good cycles, developed 667 ft.lb., but these were rare
- Combustion process became unstable and extinguished

**Key Insight:** Cylinder failure during a run indicates serious combustion problems that must be addressed to prevent engine damage and restore performance.""",
        "keywords": ["cylinder failure", "nitro engine problems", "combustion failure", "engine misfire", "nitromethane issues"],
        "topic": "Nitromethane - Cylinder Failure"
    },
    {
        "question": "How does peak combustion pressure location affect nitromethane engine performance?",
        "answer": """Peak combustion pressure location is critical for nitromethane engine performance:

**Optimal Location:**
- Peak pressure at 10 ATDC (After Top Dead Center) during good combustion
- This location provides maximum power and efficiency
- Timing is critical for optimal energy release

**Location Changes During Run:**
- **Start of run:** Peak pressure located around 15-20 ATDC
- **End of run:** Peak pressure location shifts to 20-25 ATDC
- **Shift amount:** Approximately 5 degrees later in cycle
- **Impact:** Later pressure peak = less efficient power generation

**Why Location Matters:**
- Earlier peak pressure = more power (better mechanical advantage)
- Later peak pressure = less power (piston already moving down)
- Location affects how efficiently energy is converted to work
- Optimal timing maximizes torque output

**Cycle-to-Cycle Variation:**
- Location can vary significantly between cycles
- Substantial increase in variation as run progresses
- Indicates combustion timing instability
- Affects power output consistency

**Combustion Timing:**
- Location shift indicates timing issues
- May be caused by ignition timing changes
- Could indicate fuel system problems
- May result from combustion chamber conditions

**Performance Impact:**
- Maintaining optimal location = maximum power
- Location shift = power loss
- Consistent location = consistent power
- Variation in location = inconsistent performance

**Optimization:**
- Maintain peak pressure at optimal ATDC location
- Minimize location variation between cycles
- Prevent location shift during run
- Optimize ignition and fuel timing

**Data Context:**
- Measured during competitive nitro engine run
- Location tracked for each combustion cycle
- Graph shows location vs. time throughout run
- Clear deterioration pattern visible

**Key Insight:** Maintaining optimal peak pressure location and minimizing variation is essential for maximum nitromethane engine performance.""",
        "keywords": ["peak pressure location", "combustion timing", "ATDC", "nitro engine timing", "pressure location"],
        "topic": "Nitromethane - Pressure Location"
    }
]

ARTICLE_URL = "https://www.tfxengine.com/NitroEngineData.html"
ARTICLE_SOURCE = "TFX Engine - Nitromethane Engine Combustion Data"


def main():
    """Add TFX Engine nitromethane data to knowledge base."""
    if not KB_AVAILABLE:
        LOGGER.error("Knowledge base modules not available")
        return
    
    LOGGER.info("Initializing knowledge base...")
    vector_store = VectorKnowledgeStore()
    kb_file_manager = KnowledgeBaseFileManager()
    
    added_count = 0
    
    for entry in NITRO_ENGINE_DATA:
        try:
            LOGGER.info(f"Adding: {entry['question'][:60]}...")
            
            # Add to vector store
            doc_id = vector_store.add_knowledge(
                text=f"{entry['question']}\n\n{entry['answer']}",
                metadata={
                    "question": entry["question"],
                    "topic": entry["topic"],
                    "keywords": ", ".join(entry["keywords"]),
                    "source": ARTICLE_SOURCE,
                    "url": ARTICLE_URL,
                    "category": "Nitromethane Engine Data",
                    "data_type": "combustion_analysis"
                }
            )
            
            # Add to KB file manager
            kb_file_manager.add_entry(
                question=entry["question"],
                answer=entry["answer"],
                source=ARTICLE_SOURCE,
                url=ARTICLE_URL,
                keywords=entry["keywords"],
                topic=entry["topic"],
                confidence=0.95,
                verified=True
            )
            
            added_count += 1
            LOGGER.info(f"  Successfully added")
            
        except Exception as e:
            LOGGER.error(f"  Failed to add entry: {e}")
    
    LOGGER.info(f"\n{'='*70}")
    LOGGER.info(f"SUMMARY")
    LOGGER.info(f"{'='*70}")
    LOGGER.info(f"Total entries: {len(NITRO_ENGINE_DATA)}")
    LOGGER.info(f"Successfully added: {added_count}")
    LOGGER.info(f"\nTFX Engine nitromethane combustion data has been added!")
    LOGGER.info(f"Source: {ARTICLE_URL}")
    LOGGER.info(f"\nTopics covered:")
    LOGGER.info(f"  - Combustion pressure characteristics")
    LOGGER.info(f"  - Combustion deterioration during runs")
    LOGGER.info(f"  - Cycle-to-cycle variation")
    LOGGER.info(f"  - Pressure comparison with gasoline")
    LOGGER.info(f"  - Areas for improvement")
    LOGGER.info(f"  - Data analysis capabilities")
    LOGGER.info(f"  - Cylinder failure analysis")
    LOGGER.info(f"  - Peak pressure location effects")


if __name__ == "__main__":
    main()

